apiVersion: apps/v1
kind: Deployment
metadata:
  name: markitdown
  labels:
    app: markitdown
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markitdown
  template:
    metadata:
      labels:
        app: markitdown
    spec:
      containers:
      - name: markitdown
        image: ${REGISTRY_PATH}/markitdown-api:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
